[[FuzzifiED]]
arch = "aarch64"
git-tree-sha1 = "4a2325007fa66c65cd8d1a17269c42d40eb5ba47"
libgfortran_version = "5.0.0"
os = "macos"

    [[FuzzifiED.download]]
    sha256 = "bd0551dc275d09dce9411dfa3af65579c014508c6a8681c624d323d7a2e7e4e3"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.aarch64-apple-darwin-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "aarch64"
git-tree-sha1 = "e54b844fd697db7cd220b7b6dd1ebde75bf47375"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "aecb50bc3cb49d053ffe91417dc81d8281a9db9ae51d0f9e27fd5a42d57ffed8"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.aarch64-linux-gnu-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "aarch64"
git-tree-sha1 = "12ec7081e14b9bb3f14fa6e18402fa844b577fff"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "b1ed5d5437f531dfcaa846456facbb02092ec00e7573cca63ef86ea52e9e3245"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.aarch64-linux-gnu-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "aarch64"
git-tree-sha1 = "aa129d998ab593acc3591882144d11516332c4cb"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "6a7423ca7b8b6ba38e2829de31209ae58060b7c7c84d6f33246a589228d3f2e2"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.aarch64-linux-gnu-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "aarch64"
git-tree-sha1 = "a2c0fdade2a5cf1c88fc9ca683de060214578a72"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "3e1b167f56f776ba07e149a4bbba69f62db3b6baf4708b9039609fa86793abb6"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.aarch64-linux-musl-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "aarch64"
git-tree-sha1 = "dbd224f54699c46b6a1a5f4fdda612f1752ecafc"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "63df0bb8cd255921329c580e3b074528a961c261488c9a55e10f96318ed9fee3"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.aarch64-linux-musl-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "aarch64"
git-tree-sha1 = "bfd2aa4a9de92b1083e1cca71183acb4e9102cc7"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "1ff4b00b7fd49a3a67be517cb4ea28eb096e45ccfb876af7b0bae101ada3731f"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.aarch64-linux-musl-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fe46704a8df952662462fb2b58e3bd545d870d40"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "cec183c5c7dd8fdeaae866fd7f534ac231501cbe468d3af3cfe5852ca319539b"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "24288d9a661a1d71f33358ba1486139c0acc262c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "000cbfe293f235c1d9181d04de7839544ae8792cb25e2d635e00e69d2733fa69"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7d30fb38fc5dc4d99a01f31f5852ae1a8876bc1a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "54115b41af71e0af445320237c92cc6f968ca6d679f59a3eb08e9da1d56b4128"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "41ded21126d602cf6e5b2c84420084bea6f1ebc3"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "20f8af2f88f5afcf600330fb78e2090ca6995b28a35fa108e8181ef923bbbf14"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "767c7e1fcb0129b672c6688cec4ecdc30770fc70"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "a93efe225023411e040440e8668be281689e176afc872e7659dc1eeff39f9a04"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e201b1cc94cd8b0dae32d28b23fee25a384dc47f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "debe6d680f29ffd3546cec433ae8983bb55eb18b2687729c17de55d19a9f4fbe"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "330261d6bc3f485c91fa2f23a7386b1484fc4081"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "6c8ee07b3fcfb0894696df1ef045fc36c9ec3661941f470b24ebb348f2429632"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d3944593833cbc654b06518adab199d3e1fa69ed"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "610cf32414476b3d5ef0b10d263471764f4b7f8b98ceb2a7f75151420c8a52ce"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a220ee5fcf3f9c6b6ecf68ec619781db639227b6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "c243e0082dff68001f75dc0625d7dd98b0a678e00854b1bdb49b1328e1da711d"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c00c173157a10b79b3043fae2a34421b6f522587"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "96e29a125e6fd94a7b4ee6c6087e067c3f9302e9eeecdd2a1be1784a9861ae62"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "32e1c92ac1797b5fbc9b89b8d77f73e7287a8924"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "e92fcc38d61935355273e415460458cf30c633c221ed2b4543094000d46fe4cb"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5d2ddd94649abf38beb40e0fc855e265d6b4ee12"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "05dd351576ed6edfdc1f85f6abcd3adf5f76a706cc1ca4d8843ca276dc922d08"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "abc77af9957bee8e2086eabfc360b1a97f99ce2b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "df5feb0372b9c9cf99d7b2518a38817e5a1e7673b0060a2810e994a7bd6d988d"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.i686-linux-gnu-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "c41f6188546b8a99afa5801ff2ac041f91e257e4"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "9352eae5b406e9f2d64ce22219eefccfc50b5a2b50b18379b196b8ee4e70b9ed"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.i686-linux-gnu-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "0299d4828faf1f908ce436e02527d64989ffec29"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "c0039deab4e2eab1b0224fce8d82aad5a6e89008a0c5bb1c93e270f8504b3b77"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.i686-linux-gnu-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "a0577009798c26e3eea2a4fa81a927f3701d9237"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "0129e4423720814b53b0fa59a65328ad9c0e8ea46e74c4ddc31c593b54a00ed9"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.i686-linux-musl-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "5eb02722f5e43dfb1708bb25b85445acb371c636"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "34718c73af6f8201cedb58835e2d5d0dac2ae49d6cf74b06a082406e82ac2c1d"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.i686-linux-musl-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "82e87fdc6475332c75437ab76521cedfbf505679"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "5c5756833cc6b7b9fc7b9f4325593edd773b81fbfc051725cd6ef0dc6550bd2c"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.i686-linux-musl-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "1c7a5959e42917988e5fa3af5d7250d5ce4530f3"
libgfortran_version = "3.0.0"
os = "windows"

    [[FuzzifiED.download]]
    sha256 = "ed7727f121ab832cc1a656cba66f1a5852bdfdfdb1b80238c4cf90e79303cc6f"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.i686-w64-mingw32-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "dc1590e0e52fa11904b55471462684920f368131"
libgfortran_version = "4.0.0"
os = "windows"

    [[FuzzifiED.download]]
    sha256 = "946a7bc8b0055a1188bed704dfe841f01ab45144554cc83038f8698edf64196b"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.i686-w64-mingw32-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "20accd0356fa784e277f0078224c8ba88c2c3a30"
libgfortran_version = "5.0.0"
os = "windows"

    [[FuzzifiED.download]]
    sha256 = "febad849e582ba804f0e1614aca0d02fae25000cf02722c2d4a688300e76c607"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.i686-w64-mingw32-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "powerpc64le"
git-tree-sha1 = "293263012c5a73a8b5752e84802eea7353258591"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "7d41fb994d4b4359a740df212d8a3c7f62ecabc58b4d07a9a78a3c150600581d"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "powerpc64le"
git-tree-sha1 = "86627ae857465a9e3cc42c45b552799a601d5664"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "5f8748b39eef37abaeb12e8f18efe76d9955ad67e0d926af11b045ab1e2ec635"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "powerpc64le"
git-tree-sha1 = "a1472a9faa3e76c00c55bae34b2bc43a7f607c1b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "51b6823fd2a6dfacd96a58309d96346a8375d76bb43a7912406de5fc4666af85"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "750a81c8df636fe75fdeef6576c6b115d77b5ee5"
libgfortran_version = "3.0.0"
os = "macos"

    [[FuzzifiED.download]]
    sha256 = "ea9157704de264ef19834f6b90b677ab5f9fd8e8f0565176602bf4c09c0686a4"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.x86_64-apple-darwin-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "1c0fe7e101510d0a92d1d9933d9ddf5fd75e54fc"
libgfortran_version = "4.0.0"
os = "macos"

    [[FuzzifiED.download]]
    sha256 = "4bbe9df68f12ccf929269c9a43163934e67e5885be6aa8c5abb79ec0566c58d3"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.x86_64-apple-darwin-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "9df862a9733a31a80087bdc26b01a0b1c3acef85"
libgfortran_version = "5.0.0"
os = "macos"

    [[FuzzifiED.download]]
    sha256 = "b187267a1909d4fc0ab042ae0585af8183cb2e8dab4b2e8119b7d7bf61c07aa2"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.x86_64-apple-darwin-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "47b948cb711b823fad8908bf2a4e06a0abf718f0"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "57a133a1c132043eefdf329ab74bf8418b7b1be15e49bedf178394baa605ee9c"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.x86_64-linux-gnu-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "697370722352f2e25ea8ed07d9a917df414f3afc"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "31dde59d2c832f85562bf5e6910197cb513bfec299d55b4873a3ac99435b777e"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.x86_64-linux-gnu-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "364c1f89a0be5368e774ee008b0f1faa912ad6f5"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "7b96aaa528eea693d9e30311cc9638033580480d359536e8fc02bbb0e17bac56"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.x86_64-linux-gnu-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "d9d41090ea92ecd8df2a756b307a249f175274ad"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "b5a6c0990c21f28093884fe564b248ae664676b6fe723d08ddae1156d60c8b8e"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.x86_64-linux-musl-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "0f74c08d8850000919c48c4e8296c62ed4cfec16"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "44f015fcbd10ab8ff957c71dffd450e923a58c2710a184d3caf0ef8ff6b5ae12"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.x86_64-linux-musl-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "311daf63af110d64d8acf3a3c59fbca434f1b1f0"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "7bb53749a83c1edf0fa25fa65cf20bac1c42df691b84c6e05c5bc0e4d2b1308b"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.x86_64-linux-musl-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "831459e510038a1bfc8918f3a4c36ac880e7fe8a"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[FuzzifiED.download]]
    sha256 = "1c5451d4fac2c6c9d63aed1cf0b8061e2118a477566cb9cb8ee11d2e998c85b9"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "1d115f9b71f19b5fc1fe66b5c0f6b7c8b49d8673"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[FuzzifiED.download]]
    sha256 = "2d0a9d8fa882892f7a23010327c3adc09b793afb54259992a86e0a5941607154"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "9eef760f25e66062c68ae92b9c3e410cb665a452"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[FuzzifiED.download]]
    sha256 = "0eef0334c002484670b57269b7cf6a8799eb659f0f379dbe5b203b33ff29b383"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "2e26e3a38d2939f48d6be284fb883b1bfd97028e"
libgfortran_version = "3.0.0"
os = "windows"

    [[FuzzifiED.download]]
    sha256 = "7b04dbd6891f145cc7e2ddbb8fe74e3097a947a07e8df3b08a215319aabdee09"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "4543015dbffb008dd026965b9205c6ab39f6cbc5"
libgfortran_version = "4.0.0"
os = "windows"

    [[FuzzifiED.download]]
    sha256 = "0d19d1a23c0930cf6f10d3b4c62c19c79abd45880e2112c1615d0a0a2ae0d3ca"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "e8ad2a6d1cc2ec857ed647b109f2898db8348ef9"
libgfortran_version = "5.0.0"
os = "windows"

    [[FuzzifiED.download]]
    sha256 = "5ccba7027aca8d26ee03536f54e73638b938c748839a9ddf809bf430dedc7b15"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.5+0/FuzzifiED.v0.10.5.x86_64-w64-mingw32-libgfortran5.tar.gz"
