[[FuzzifiED]]
arch = "aarch64"
git-tree-sha1 = "fa6bdf06e534c2cac9fb064c71f33b4421880c08"
libgfortran_version = "5.0.0"
os = "macos"

    [[FuzzifiED.download]]
    sha256 = "571ff0691e4736263fc0bddb6433e109fad1d7ad1941822ee5393b9395213ee2"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.aarch64-apple-darwin-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "aarch64"
git-tree-sha1 = "878b57ee6fc4e4c12b4c1f21cd2afd61cbfadf8c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "dbfd4c8626cf0c25cf2a30ac21c47b34551ab1c60d652d06270c4760182b3fa1"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.aarch64-linux-gnu-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "aarch64"
git-tree-sha1 = "cab560ee542c7946af312c5c5c5c3588e8e3ee22"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "685771d2bbddda3386c435e1f93b13ad1bb92d874e74ef26758793fc0efac6d5"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.aarch64-linux-gnu-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "aarch64"
git-tree-sha1 = "75d5285ca37ce646ae65a761ee5b0c2492509dbc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "979afd4dc31ccaf6e50e6e1ac805276e20b730950b11dcc362cbfc3793618639"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.aarch64-linux-gnu-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "aarch64"
git-tree-sha1 = "8a66238301d384490628b4e888369931db067fe5"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "fe5d5a2ac22ff733776dd4868d73540c6a6bbd54ebc162a1aa90591780e9899a"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.aarch64-linux-musl-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "aarch64"
git-tree-sha1 = "31d0cf073df64324fb3362ddc6a800e6f1a94918"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "8de03bf82519b14d2fd7328067dc139e4685ca8f7ccc62a471ec2f21761e2ec7"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.aarch64-linux-musl-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "aarch64"
git-tree-sha1 = "f5a35e715df96066badcbb401307e6c129cb051b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "13ba337ecb9905022222c66c1cd83648b920655afb900ea40171fbfa992f6a9b"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.aarch64-linux-musl-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bd8469b194150b41857579c93d1835822121d52e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "5e2cf52c9c34d766d5702e99e8a19b65c61c4dc7f2e66c4c6cfa793973089d4a"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "23c496c6fd2a7e22fb36ce5c86a6660d78cedb40"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "30ec70db3d1d4d90c9a504d008b5e88813340aac2d868e1e8642c1154bab9cdf"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b0cb3b7ce3ec4039b49f010ebb1e519a7df1b1ef"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "f18fe110bf41295c1090e73bb53906b90261d66f4a8880421ded60b0119818a1"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d63ad6b7e9a4fada327fac9507e2cf265d40ba16"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "2e0022b8b7fb9e4bfa710c57d163cd8d61f57801246fe9b7f2601897eaee23b7"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "aee9c6b4d198cf4bf787c3babefa7f73fefe11e5"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "f1a7e6c880f0fbf84aa1323a3ba1c07420de0845a4ff4b73135a710b945df119"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d4828e2feb60ecbdf87901319ecdb725a25946ad"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "bb1ce07e9f2cfe8b3f8b3b9267a99ecbc9e2cba23be1efd70b65ee48947fde10"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "04e3c46ec8dbe774de011e77d19ffa03cd7a5185"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "eb810f55217dda98da0b8ad5b266c722408f2e4c9828404a263af9e7d526609a"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ef25268477cb157f2860fb0d7a2eb60fe291b110"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "05c3abc2bf097be6e124dadb674fec290de8c3df863b7615cda405e5f88e6904"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f2ea920f1d3424cce925095ead3a683e25774edb"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "a3bf91e5b98a8c3c6a9ea48c5aa99dcd9f38d857b202c3462ca556823b35c538"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7ed56b3a8f03da2b11061b4ec197410f71a1f8eb"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "dfacbada6769bca687e0d4f5779ffd24e439dc3166741817dbf0df0e899a36de"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f7fd58511d1dfb4b98bd8aa1b7b8b05f29df5ca1"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "aad7d111eb4dada039f9e32c3a1e0acc9dba7c5db04b5fc829e386c7dad67716"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cedf39c2c0f68d2438cd69039ed663690436a4b8"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "3d464842a4d4393a348413f57d446ae1d7cd12d3035ced1f3a788b07f3ae56b3"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "7a72f39843894188bf272cfb7bbce64ef0a232a0"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "d95c9cab25499afa21f3b0dfd35a7c0b56c39ea6560e5ae465ffce36ba1d76c2"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.i686-linux-gnu-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "0571637f56860fca23b377a80e95da80f586b647"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "74e1bc38c51b71c646322fdc4ccf69a8fb6e929b92fc97b24b65cff520aed712"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.i686-linux-gnu-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "65c06b8008a963a827184a2397f4cdcfe3beeb98"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "eb516417a9af72d6e7eab48ff90517b999cd265dc286c8866771f3f9c2d63e86"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.i686-linux-gnu-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "d700ab961474f0cb21c61742532386ec3e7fac27"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "d1591132e28859cc352aef726bebb2b3c89a2c081e302e3f18da7a5b4b4f100b"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.i686-linux-musl-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "2e3a5a2e82d330f9dd54f05f068be77a06724f49"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "9cd737df3c468bf161354596f971768f5263c608175bda56936e3f898ecd02d3"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.i686-linux-musl-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "af8e75e7dc1a67312051b113f7853521c8004186"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "6c7849413792902c61cce9af96a172aa7d2eb66ed49784069bcb813f0be48a40"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.i686-linux-musl-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "47c7640390fb4cf519716118bf9139dc5f767bde"
libgfortran_version = "3.0.0"
os = "windows"

    [[FuzzifiED.download]]
    sha256 = "2fdafc01c75623c754aff36cf0c962f725c4d7381ebeddb51d660ddf90071cb1"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.i686-w64-mingw32-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "bd06d722dd3856717855d644a84fb02ec9dd3eb9"
libgfortran_version = "4.0.0"
os = "windows"

    [[FuzzifiED.download]]
    sha256 = "1ea14a732e4c7f53d336f423e68a963aec605ff4cc6c6e405310462be37ce97a"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.i686-w64-mingw32-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "7b002f8f69c25c956b6e9895b81dc1ef49f0455b"
libgfortran_version = "5.0.0"
os = "windows"

    [[FuzzifiED.download]]
    sha256 = "abc530509b642704888d10d8204b174f02c05caadb1bcbbf0a5a19ce4ec96413"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.i686-w64-mingw32-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "powerpc64le"
git-tree-sha1 = "c4a3c6041b3ab0947cebbf1368a0bbbd111d41b8"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "394a07a84dead7a9a8085986aa8c727e40143b135215a5ca5593550fe409dcc4"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "powerpc64le"
git-tree-sha1 = "8d93c49df4aa98a7fbd3006899f653b7f271c497"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "7083f3810dd25ab9de7cf0762cb896fca9159d1c503451dcaf75612b7aee127f"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "powerpc64le"
git-tree-sha1 = "47a61e0c43ccddb585c564cee565cc970a618682"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "3851209a1c5fd0b971c16cdbe63e6f47c1f477428098f326630cada8e4e53dae"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "189be0a1c337cef9e65c04d8aed4cc3919e3d95d"
libgfortran_version = "3.0.0"
os = "macos"

    [[FuzzifiED.download]]
    sha256 = "759a32a64ae7ece5bd01663201f9ac608e137de57e5620651b22ad184037e4e2"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.x86_64-apple-darwin-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "dc282ad77ce9be9e3015e0692fe55b63d69057d7"
libgfortran_version = "4.0.0"
os = "macos"

    [[FuzzifiED.download]]
    sha256 = "0811887bc0aab3850efe34400bd3a4125393da2f6415e938a0d2f6d24514ab22"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.x86_64-apple-darwin-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "1e0cf1a37929bc65c6e9d659a378f208e2b21df1"
libgfortran_version = "5.0.0"
os = "macos"

    [[FuzzifiED.download]]
    sha256 = "b17334dea22ee55bdfdfb6e230ccacaaff1fc99848c0df929bbc800a60fe996a"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.x86_64-apple-darwin-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "dcbbbf17916f1e263eca2b089922b1044073bd4d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "2634bc517935b2f41042b83ad4d536198f70b9c9b5ac5106157b298ee8c3ba9c"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.x86_64-linux-gnu-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "135f52f5f015e8f5cff76201d8489f8d47c2a31a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "d0d3d2b94e1cf71fd785651f2cb1f74de2b50a682e3406dd35ddffd74c99f5bc"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.x86_64-linux-gnu-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "e651bad38573151e419ca702f520e4ebee5fc36b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "eb473562fef1b9f2509a2434d7c104c48d33aed453243081bab5f977fbc67cb1"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.x86_64-linux-gnu-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "e4dde249664d37837b59686abeda71e73647de4c"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "f930ebbcdf424f4da6fafd6fa86c683d3a3b0eec8116e608602a509cb14a5665"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.x86_64-linux-musl-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "bc757e9f0b3157c64b947335242cb25c9a1f5648"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "7e72208c1c8839b254e6c3943531da4d75ddfff9b9b51d031a07c789aea4e1f1"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.x86_64-linux-musl-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "6cf8db28f281900563abdb9c10a919f397af94b6"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "137c7d43945504f86a4b8f7e2f64db8226e22dfb6c6f538a4306368d5bb8f16d"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.x86_64-linux-musl-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "f2b443690aaf67ad9adfeea4e371eaa4ffe07859"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[FuzzifiED.download]]
    sha256 = "d14ca74c1cb519eb53a560462fcf3346c2df28ab56df55726ab3364e99986aea"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "7806a5bed4b84b78171dbe6017337244d8bb3880"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[FuzzifiED.download]]
    sha256 = "00ad0a8e4b3d12f64a0b5ec21a6298461545216d0097bd6f62058dec31ceb1a2"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "4cb2767283410a4b5063b9a18b4f5a864c472914"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[FuzzifiED.download]]
    sha256 = "edfa66eac9ef516539153dae7f4b428b8d9f3ee248962330aeeab976dc239324"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "9589138527d63c196cc65461137abb289dd91ac5"
libgfortran_version = "3.0.0"
os = "windows"

    [[FuzzifiED.download]]
    sha256 = "be6a9d5befc553d57e4483d861c5b0b38a4dd5f737a8c26f6a595cc2f4203ce7"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "2de9dd10056923aed1cc68cce67cfda0b214a70c"
libgfortran_version = "4.0.0"
os = "windows"

    [[FuzzifiED.download]]
    sha256 = "c9b47eae76a7fd8034baedc6ff865647e9e3b6962396085455c67f9b3de59e3a"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "b11e112e36c346c36035b79d314886b04e82f587"
libgfortran_version = "5.0.0"
os = "windows"

    [[FuzzifiED.download]]
    sha256 = "ce1d5d9b200c77a6764102aef2735d051efd87104faa11f307953bf4a6070553"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v0.10.6+0/FuzzifiED.v0.10.6.x86_64-w64-mingw32-libgfortran5.tar.gz"
