[[FuzzifiED]]
arch = "aarch64"
git-tree-sha1 = "6e5adecc22329d2701da63b4c8ab5ce9d1d35592"
libgfortran_version = "5.0.0"
os = "macos"

    [[FuzzifiED.download]]
    sha256 = "08adbc7b07905f5756148f7b17ad23733a927510ab5dc90eac85a9196354b111"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.aarch64-apple-darwin-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "aarch64"
git-tree-sha1 = "b1f1f8f08061901a14659a988ff055821d50d2e8"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "2c8ab67c60940e789bbfe7a89d5bca7cd9da21234480ae37b48800b0600818e2"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.aarch64-linux-gnu-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "aarch64"
git-tree-sha1 = "6d5f748949b202ebb50038ec07cdc195ae0d1cdc"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "cd1b1c5f2635de737e3995717a2057e866663d75596f3b90acc11adb08361da3"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.aarch64-linux-gnu-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "aarch64"
git-tree-sha1 = "24611621e33271297ad40b28e4dc580b4f659192"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "0f8d9fa3e0f2fd1ceabcbe50604b431739d64f1d0bf4e5f844489434e1cce012"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.aarch64-linux-gnu-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "aarch64"
git-tree-sha1 = "56ef67eef3c908d0ec1bf5afe02ac4cc76b5389e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "1d4c74c1c2c6a5861596042cf0292e590acef1176ddcd126d5972c61a3b5de9b"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.aarch64-linux-musl-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "aarch64"
git-tree-sha1 = "0ef91a9a9af4c87ed3f008252ebf160ef9708763"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "64da648f892908450a43cde7b13ff246d7df46a69026d5711f1531a4e857406b"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.aarch64-linux-musl-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "aarch64"
git-tree-sha1 = "aafdf9bb13ea100cd15875a9edd7337222eb0b05"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "9375799588ff6cec21023545866f65f564bc689831887b7fb19316c9c2d67355"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.aarch64-linux-musl-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9d632392cf4ed162d5168ba04bb6a8144a747ca3"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "cc02643440ee16abe655bf58daa642babacba63f2bf6b17246457326684b8a33"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ef6863864f538387166f51d3d187e212efd81c4c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "56a4e4b3582ebbc3861ccff8d5bf1e46413a9b38f92a2fc1006a7bfabc09a82d"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cb29517994a5cf60067014572cdbe81313fd6472"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "2f6e9c7704a8f604d600512221fd23f55dfdb60760ee55835f40ed175c734c7f"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "556bf6b2ed5abccf53d0c7be56c58286565d7ece"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "e104c2cf1582d085d4348b48db1f005e89e88a81f9937307c8f618d48cfbc431"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b497d1749e17933eccd2f8b6649bb3e67ccebce8"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "939f456d9f0b2d75c511822018e4d99266eade5ef613dde7043ce853d48c342a"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "702c8bf0f0ea1c93fb9d5aa1862a2c0e0f759d9f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "456504e2fb7662f6bf0e6d40837bfc72c0df4a7513c623f2f92e351713b0f35d"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "11000e2f64614ddf66e0a6da52a27067e3c4f3a1"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "bab971faec69f423045a3341fedc5efd1c35fe345be78990ace214cd5eae6724"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0babf539aedacf06fc43719d94b1909094c752e3"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "d7496283cfa8a655be1bf0a754417849fe2f88be97d8557323e44ab6dde35087"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "97fabd8a1d9cb03b9d05a624635c32ce4fffe60d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "9ca94762b319d538b011625c051ffea9571a6d54a784a6bee461860ac1374519"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8ff7d79693a365f85c4cf1155dc55eb996a24b8a"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "43578ad1023fb4d776fbb2709ad93bebade6f4a36a9cd7a850b1532e84efae04"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7d2296bace7402688ac74695842e2322edc6d3a4"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "4a9482734e65509f3b534885a79810d7f53b5d5134899d64778c2cbea23b9dbb"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f2c137b1d52a2f5723f2f679f42f291e7194c7d8"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "92c107dd4eb1f5fbc15715a6d9ee4c9cdedf19b6a4eff894544e9dc7ece7c716"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "71690ad2b53bede0bb02e104df3d37a7a0a62b29"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "015fb10a8c061a9a2560069fc7f77aa5051714b4861f6ea4d9d6b53b043acebf"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.i686-linux-gnu-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "b432a3010d6cb6f14cc3b901fecb485cff167b5d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "9100de2971cc34a948d71cec7f7e85b0794940a4c95383c0c84991dd099609b2"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.i686-linux-gnu-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "e03065843a1f95f5f57d2622610e468b52631f88"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "aa9861870c9096b64e4b7067b0674e85ad57c92c2b0b70155db9b622ca09c138"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.i686-linux-gnu-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "cb5d046af417bc011734fd485db6e6f1c1adde98"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "f47f6e16e55d9985f0c4fefc54cf74eb84eef6636a7e09a260c446257e44d30b"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.i686-linux-musl-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "eb988437277ef0a62a3c720ff1d21cff18b85d4c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "c9c5d6e3f781acd868097046bcfd06cf3e85dbac63dc18ffd5db4375fd84dda1"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.i686-linux-musl-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "f48b2a160dd745c874765a4453a96fcbc578b6fe"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "13157cfcbe9a53a0c82030252dfcc923f5bb28e891410633ca87de7d5b8ad41e"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.i686-linux-musl-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "c102b48c2ee7d2a77361b073f7b40b74bbd99fc8"
libgfortran_version = "3.0.0"
os = "windows"

    [[FuzzifiED.download]]
    sha256 = "bde1aa690bf153c66da14890a9ecfae6ed7fb220f0c88f9ac17ad7c41e4cd902"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.i686-w64-mingw32-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "885697bc004c23591b294550744cb8c738e3f529"
libgfortran_version = "4.0.0"
os = "windows"

    [[FuzzifiED.download]]
    sha256 = "a5469001b4f2ce8a77c214ee9b82a68d4ccb2e44fc4fada6d6310af6a266aef6"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.i686-w64-mingw32-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "4ee9403944d2c70402fcf99693ffd8628971e721"
libgfortran_version = "5.0.0"
os = "windows"

    [[FuzzifiED.download]]
    sha256 = "2b61e7e56d8d4392d45230c3e9d525fdcc33e29852a31eb460956d93367c2fe3"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.i686-w64-mingw32-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "powerpc64le"
git-tree-sha1 = "0a60b8f026d913d64c4c3c53335f7a5b62fb4d1b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "a758d71c8e8980293f85201315db3c06c5ae758379e5ea85981747dc7f91b7c7"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "powerpc64le"
git-tree-sha1 = "9789a0655783e50dc3e8db76a08c25070366a066"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "7fc01c47c1d61827790519f1832a9a09e5c068b8077bd1cab5ca2acc193386c4"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "powerpc64le"
git-tree-sha1 = "8807c0e21a4727771f704551b8438158b7b43735"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "0c6716462016e9c1a3e017f9465e5dc903d50e5bdf7075da7f51e1cd979957c5"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "4d9ad4117e0e7309bc24ba785c354f9669ab1b58"
libgfortran_version = "3.0.0"
os = "macos"

    [[FuzzifiED.download]]
    sha256 = "8a1ec3594de1283d253d940b923a061055806f833aa58855e059068ec0acd74d"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.x86_64-apple-darwin-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "4c6cb19fd8c13e297fb8eae6ed411c9aae825cef"
libgfortran_version = "4.0.0"
os = "macos"

    [[FuzzifiED.download]]
    sha256 = "9b306132bab72357ba960d6c6466af167c407bcd6ba3337dda8f7452781c4317"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.x86_64-apple-darwin-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "170db3f0ea6d21d010b3388043c12cfa62411675"
libgfortran_version = "5.0.0"
os = "macos"

    [[FuzzifiED.download]]
    sha256 = "cc295c40ccbd80c880a047184184c64eb3aa0a791ac64c8b03465e7675d57f9a"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.x86_64-apple-darwin-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "a0ebcd808e4b45a6921dba423bd22617fa6327ae"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "45c377639bca8d468cfd5073cbdb1f0d3b0bf3830f52a87784a7c261493a7898"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.x86_64-linux-gnu-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "1f378b41567e773cd2b2bc5a0d97a8713c672066"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "2d95e5f1b6528500d75b3231620f7016612847e1f58289cd4bb64e00787b6f74"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.x86_64-linux-gnu-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "985ba8e57e21c994733883fcbebd4baa802f23af"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "63f4cc016c84294f24e858a7551e8f9f2abb54419e6c55d07d93cc7f57d15a8e"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.x86_64-linux-gnu-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "962d18fe74e324e0e84661224db90b73c6fbe8f4"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "043b8e8ec62436596aba6c7691968d6e493e8abe557a6ad87e6a19f7755f3f10"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.x86_64-linux-musl-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "c8eb4f574009182e845f6f925b64afc1541cc3cc"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "447f3b67321f3114d6750ac991ce37dd5a9a9f55fc86b85b5ef71ee49cb0df14"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.x86_64-linux-musl-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "6fa9d45c499e1067f39ec64a3cad0aca2c5e7f3a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "080e08965a0e6b6e8ebcec4ed45568517df1c0cb5b0f3f388334902bea9d149b"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.x86_64-linux-musl-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "2fff9cc90f675312c75e8f4527d2852e33e7fbd3"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[FuzzifiED.download]]
    sha256 = "b41b00cd42dd1a7af7e97b769b43246ab1648aabf0f5b9693ccb3de86160adb2"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "414c5d617ac8a3cfac31d6e9c8576d385a8b20a7"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[FuzzifiED.download]]
    sha256 = "6f0662bd177d991ca05ab35310cfd4b060c900a539ebc47f3a8d7680e23bac90"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "ce458af86cdb861fddad317efb565d05be7f26f9"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[FuzzifiED.download]]
    sha256 = "15c0c808485cd77ce4a6b842fcff8ed388b5e9400bb1ffa9a452365db61d9ec1"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "f829000ea323e8186e5f24e700112e4b4254d57c"
libgfortran_version = "3.0.0"
os = "windows"

    [[FuzzifiED.download]]
    sha256 = "0adf156bb9970dda0fe04f1d810b58060c5b9f549dfe636098592d8f60c3219c"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "93b2183da52ec57a4713fdac850efac15c055a42"
libgfortran_version = "4.0.0"
os = "windows"

    [[FuzzifiED.download]]
    sha256 = "b7448185b047e47ea3a10412d80524603f6897fd9e81093d9b7e3eff435271cf"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "dde537ba876a615df71fe21d6e23d6bd096425f9"
libgfortran_version = "5.0.0"
os = "windows"

    [[FuzzifiED.download]]
    sha256 = "664fe0f53323cf49b3502ea0287e0916d7f196b81290051836aabbd8d0ccb52b"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.3+0/FuzzifiED.v1.0.3.x86_64-w64-mingw32-libgfortran5.tar.gz"
