[[FuzzifiED]]
arch = "aarch64"
git-tree-sha1 = "c1b71a37b06c05a4f8d3a54e6f0cb5cfaa75bae4"
libgfortran_version = "5.0.0"
os = "macos"

    [[FuzzifiED.download]]
    sha256 = "84d93bb0e6da36168db9357183092d611478a8cd3a5ca6ae66c6e3399e3b59bc"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "aarch64"
git-tree-sha1 = "d3d5fb69460c83cba9746f5f7db32221694e86aa"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "c455d7f1069ed8fba08c03455d177108b3b6f5ec50d3f5fca39842dff5202895"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "aarch64"
git-tree-sha1 = "ec5978d24cf583bd69801de1c26c8cc9afe30be6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "b9fd25f6b85565d67428b549c458338c8a3d0e00c2f2bfec38b03dccc6cb501c"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "aarch64"
git-tree-sha1 = "95c7d8ed1402ac3aba3e2fd5a6017bbc813c1193"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "93304055808e1c393085d38705d6b9340865021cf0f2d5c5467bf173a2ba3132"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "aarch64"
git-tree-sha1 = "f64dec41bba980ebe025990695fd6f5610b18cd9"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "58ab684d4457083bd201d0da7a8da8350e240337f394eafc269fb152b5597657"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "aarch64"
git-tree-sha1 = "2429b49eab76c269e3bd613d3f003dba630b8263"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "3b8c1f984bb89ba1adb4ff612460291a4f06f40875ed59000c3d2bed12f2f965"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "aarch64"
git-tree-sha1 = "b7f3bab2a63e8c5014f0bc26d0ea4ada73573a71"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "90ece3495a8b73ac5a62b1f4b1dc4f146f3ab1effc55b1941a4756f1f7b57f6c"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0d5a59d446377031c9a1441a78726332238ae609"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "441bc5478fb5e8bee0afea99883945f418fbb9d46527251d82520b54c7c8f637"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0f3bc10728da48224d6896fd312095b6f6d81bc0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "22b2bc150281b1741ec80f04fffb0ec8835c1398f47800baefca2fb1eaa63d77"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "23174469d1ab500807a1ee65fbba156440ed8f7e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "88cdec310e33150738ce68618e7261bbd11cc49ef2e6884f71c8b377c5b07c32"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3f7a491418b51124993d237d7cf6fee129c619d1"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "6d41977305e2b9ac7c89c5bea5348ebe2c6403574411e6962ee8c90604c56102"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bde4435c09c5be4bf6331d777654d11dacdd3208"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "b1f9b9b45f2dadbcaff2c778fb2af391873ce5bc48be9cb94fbb662d5688ca69"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b8cad662754f1796b8cf12ff07a13cc77c85c735"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "ee1e0e14b77d693971ee1fd6c07887795a2fbd1063f327b54417cd713e88093f"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6667f32d849db8a35a3218f73e57127510c9bbf0"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "b7dd366a84a59fbd657b4d2839a64abf2488e9bd8246c18eb7e67a05505394cc"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "50ffe134865166decdd6a867f84a40e29d03c26a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "18af7559391c1cb22d3bfc62c4b8000d6d12cfe88ea0492288de906f6dc72428"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "05f23d1178c37464ee51206e7d6d3c08b28e8c6a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "f40e9007b8b725654076aa1f7c60451b6d2e9cb37f6887a8940c755f998aad76"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b8e14f6f60c6c9c7e9ae30ac7c34da6cc85d0806"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "77d84ab647f0f5d892c6ab09f3bee1913818b8666bf1d9f3514dbd4d3b5a2dc8"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b3b74e2444a22f420dc30c245a7040e7831042d6"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "f09bc684667452865c7f31765c9b1a6de06f7e7bf0a03ad4d984efe3202c5cc4"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6e76447810f9be3ee9b3cad7e6a214519e5cf1a0"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "5e9476a0cf69d7c30b079cff57893aa86d74a539f2c76332f014d1554f008b77"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "1ea0a94bce2eb438baf32384f6ed67ee37583bf5"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "06eec03f29b759bca2db9730d62bbc80e7739b5d35f649d8d62edc7a5baecbba"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.i686-linux-gnu-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "b688b5da3585aca428e9c327567b3e7fefadc034"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "2fb24c864fd7b769f5d86b6f985cf5a5528b3977da699e703b7f734198e245e6"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.i686-linux-gnu-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "16d5d6e30b02027d94a56599a52d7132b57da3dd"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "9cad8a1cac67e54f5bc2c2e0f21b836feac89a55f746a5a113c10af62badfad4"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.i686-linux-gnu-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "fe5c866340d7894ae86e42aaa47d5de185213743"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "d7b14cd41367ef6f87f7780bec1cfc43c0864e270ae6120f9799ae8021aa38a2"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.i686-linux-musl-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "19e7151dab7b1920adf708661bc14c6424f9d5bd"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "4bf83488b3f4eaad7732912ddbdf96ace3eab37e14cbbbd12f585406aeca46b7"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.i686-linux-musl-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "10bc5335b96e41319baaf850be88fbead374eeac"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "395013e6f86b69ff672c3acd4b5759e3aaf74abcacd7a1aa66719eb8a2cf7a02"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.i686-linux-musl-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "43f2d985aa5b25502ffb3a13325b9969a248d9fd"
libgfortran_version = "3.0.0"
os = "windows"

    [[FuzzifiED.download]]
    sha256 = "083525d44466ad620de20e13af5854412ddc5b914ef15c81697ae802c3f24412"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "66fca1bc18422bda2dd972b1ff9ec23bb6e8882c"
libgfortran_version = "4.0.0"
os = "windows"

    [[FuzzifiED.download]]
    sha256 = "60f1de9828f61e6031cb270912348e7a705c713ef797de3ebcf5e0ef7a678656"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "i686"
git-tree-sha1 = "87defd447ea38515f66e9f907a5d3674cfc74abd"
libgfortran_version = "5.0.0"
os = "windows"

    [[FuzzifiED.download]]
    sha256 = "51242d17be5f9b59aa41310aeb768d4be17be05dd0f1bce3d9dfc23e612e722c"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "powerpc64le"
git-tree-sha1 = "54f589dc8db0b0fe800f4e23882292c057fa64c0"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "5129a64c2aa7cef14eadc3314c26184b2933cce1bfee2c381148164978962f74"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "powerpc64le"
git-tree-sha1 = "5388ff4f1eaf226aaba760c221753d970cef38f8"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "3afd79fe861a0ebadc00a2f71cad76d709fa8f0c6d5c0408f821d6a991bbeae9"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "powerpc64le"
git-tree-sha1 = "643a6bf727780fb3e41f8c1841e4fd6d4ae8f0d4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "06cf633de410d517445bea25405cbbf8048733e0e1b2d72eef13d4f131bc7b18"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "80ffe39abf80d2beb1a378450b019b332a3c4630"
libgfortran_version = "3.0.0"
os = "macos"

    [[FuzzifiED.download]]
    sha256 = "b8a9e057d062742a019ac34fc4657bc337361eadf6c464ceb7ce3e93c27e671b"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "e855a18e6e5d805e1647b0c6bcedf417cf064e9e"
libgfortran_version = "4.0.0"
os = "macos"

    [[FuzzifiED.download]]
    sha256 = "8050496d9ce6e4388fe8e40a75eba1959948dd03f4641386a8208e289c7c0f79"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "a1b273924cf7860c17c38e16fc0acba761dc4398"
libgfortran_version = "5.0.0"
os = "macos"

    [[FuzzifiED.download]]
    sha256 = "66bf74f74cf6cc1839445d481b2601f6ed627a089dc33c76ec4822b18f40b9a6"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "60fe213e93e9928c044988c381edb79bfb1227fc"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "30bdd234bac7ba1239529e0f4cc3e35b8d8d837e60fa6d9a33563d54273ff062"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "bdcac32d069d3303fcb8e2b646d8824f7b2e142c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "03a58c37cc71a0326e21d166cff67714a47247255a2592f0b069fb3c96e898a8"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "a6359c82cc88de6fe0beca8911fb353fd150c835"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "569ac932f7ec5a2ebaabbb09d88e13560f77b242c61a99e29343a70f849f7b77"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "468eb08ec6feca83a03413eda7243d9cf64f135e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "1b4e0d37c75db727940cfbefce455893628085d4eee2508376441573cc24a3c5"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "683d64e3b4d7fa3472992c4ca70b3dca177a1a38"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "c6bd34f37e8f9110c968ab18c21f67fd6c2266a1a94623dd7b5927ea6537f450"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "a166109d7c57f9ac2e2633f16623ab8ee7b0bd66"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FuzzifiED.download]]
    sha256 = "f8fece8b79d6edb30e8d4fb8dd825202bfd2c740c0e3fe982571b4fee7e848c5"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "61e3c6c439cecfb34e61e8b004bea64a2462dd4c"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[FuzzifiED.download]]
    sha256 = "b5d1c7101d2c1c611601c2bc2f843c26ae3c7c5ca12320e8a52a5e57a14aa0ee"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "28aba660aad3e3c28d259dc970b954e7c3717a88"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[FuzzifiED.download]]
    sha256 = "c789242a020c52089d68fcf9f07e981ec5fee16903e2e85a43fef09f999d177c"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "d83f961f2eaef448e1c4dd19868e4876385fa039"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[FuzzifiED.download]]
    sha256 = "78846b8866d687dc38cff37e255fa53900e8efaa514d14f09e3d82acded7bd2f"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "3bd39b17723fdeda3635b61683fa0e63052b34b6"
libgfortran_version = "3.0.0"
os = "windows"

    [[FuzzifiED.download]]
    sha256 = "81aae41e8dd35c9c4e2f80533271bf25ded8bfa7570e52ef0546a494568dc4bc"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "e6a5cffd469d913aaa6c81c645102d7852c950ee"
libgfortran_version = "4.0.0"
os = "windows"

    [[FuzzifiED.download]]
    sha256 = "38b8c0a538d6fbd14d8f89b18a983d0351abaec34d7e534ba656cf7e06d67269"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[FuzzifiED]]
arch = "x86_64"
git-tree-sha1 = "81b4a047a2d8a17e25fc457c426cd1155da1e958"
libgfortran_version = "5.0.0"
os = "windows"

    [[FuzzifiED.download]]
    sha256 = "f1ba9e29db86847e3a0fd1a3a9007db607e5783218d1a8ea5e454219865f11f6"
    url = "https://github.com/JuliaBinaryWrappers/FuzzifiED_jll.jl/releases/download/FuzzifiED-v1.0.0+0/FuzzifiED.v1.0.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
